<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Space\FreeShippingRemainingCost\ViewModel\ContentMessage
 * @var $escaper \Magento\Framework\Escaper
 */

$viewModel = $block->getData('view_model');
$baseMessage = $escaper->escapeHtml($viewModel->getBaseMessage(), ['span']);
?>
<div class="block block-shipping-remaining-cost-message"
     data-bind="scope: 'shippingRemainingCost'"
     data-role="shipping-remaining-cost-message">
    <div class="block-content">
        <!-- ko if: getRemainingMessage() -->
            <span data-bind="html: getRemainingMessage()"></span>
        <!-- /ko -->
        <!-- ko if: showIfCartEmpty() && !getRemainingMessage() -->
            <span data-bind="html: getDefaultRemainingMessage()"></span>
        <!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
    {
        "[data-role=shipping-remaining-cost-message]": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "shippingRemainingCost": {
                        "component": "Space_FreeShippingRemainingCost/js/view/shipping-remaining-cost",
                        "isShowIfCartEmpty": "<?= $escaper->escapeHtml($viewModel->isShowIfCartEmpty()) ?>",
                        "defaultMessage": <?= $viewModel->getDefaultMessage($baseMessage) ?>
                    }
                }
            }
        }
    }
</script>
