<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="block block-shipping-remaining-cost-message"
     data-bind="scope: 'shippingRemainingCost'"
     data-role="shipping-remaining-cost-sidebar">
    <div class="block-content">
        <span data-bind="html: getRemainingMessage()"></span><br />
        <span data-bind="html: getRandomValue()"></span>
    </div>
</div>
<script type="text/x-magento-init">
{
    "[data-role=shipping-remaining-cost-sidebar]": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
